### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value

### ISSUE THREAD

**Issue by backstreetdriver** [dr-sg/rscat#14]
```
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AllocationError(OutOfMemory(Device))', C:\Users\monkey99\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.3\src\device\mod.rs:308:22
stack backtrace:
   0:   0xbfcedd - core::fmt::write
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\fmt\mod.rs:1063
   1:   0xbe5679 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\io\mod.rs:1426
   2:   0xbea99a - std::sys_common::backtrace::_print
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:62
   3:   0xbea99a - std::sys_common::backtrace::print
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:49
   4:   0xbea99a - std::panicking::default_hook::{{closure}}
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:204
   5:   0xbea5de - std::panicking::default_hook
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:224
   6:   0xbeafda - std::panicking::rust_panic_with_hook
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:470
   7:   0xbeabf8 - std::panicking::begin_panic_handler
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:378
   8:   0xbfadaa - core::panicking::panic_fmt
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\panicking.rs:85
   9:   0xbfac49 - core::option::expect_none_failed
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\option.rs:1211
  10:   0xb34a54 - wgpu_core::device::Device<B>::create_buffer::h7a266640bd76c28c
  11:   0xab3427 - wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_buffer_mapped::h93adef6f76ffa539
  12:   0xa27ea1 - wgpu_device_create_buffer_mapped
  13:   0xa22fe0 - wgpu::Device::create_buffer_with_data::h1646fa06a1e42e3f
  14:   0x99db4f - rscat::rendering::Renderer::render::h47d4a8f81bee6c25
  15:   0x99ea19 - core::ptr::drop_in_place::hf88b286040cc15f3
  16:   0x99a466 - std::panicking::try::do_call::h4bcf0d5e5b7a1f41
  17:   0xbee38c - panic_unwind::__rust_maybe_catch_panic
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  18:   0x9a12c6 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::new_events::h386614a0ae649ed8
  19:   0x99f5ac - winit::platform_impl::platform::event_loop::runner::ELRShared<T>::send_event::hc37f494f2d354212
  20:   0x992689 - winit::platform_impl::platform::event_loop::public_window_callback::h0341518e744571e4
  21: 0x743d9e6b - DefSubclassProc
  22: 0x743d9d6b - DefSubclassProc
  23: 0x750944bb - AddClipboardFormatListener
  24: 0x75074ffc - CallWindowProcW
  25: 0x7507454f - CallWindowProcW
  26: 0x5d08f9be - glDebugEntry
  27: 0x750944bb - AddClipboardFormatListener
  28: 0x75074ffc - CallWindowProcW
  29: 0x75074b9a - CallWindowProcW
  30: 0x7507e1df - IsRectEmpty
  31: 0x770c428d - KiUserCallbackDispatcher
  32: 0x75073f30 - DispatchMessageW
  33:   0x99196c - winit::platform_impl::platform::event_loop::EventLoop<T>::run::h3de5d5ff62fa7ce4
  34:   0x9a3b44 - std::error::Error::type_id::h829252ac8de8df57
  35:   0x9a4395 - std::error::Error::type_id::h829252ac8de8df57
  36:   0x9a50f6 - std::io::buffered::BufReader<R>::new::hedcae91b6f0675ca
  37:   0xbeb34b - std::panicking::try
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:281
  38:   0xbeb34b - std::panic::catch_unwind
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panic.rs:394
  39:   0xbeb34b - std::rt::lang_start_internal
                       at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\rt.rs:51
  40:   0x9a4ddf - main
  41: 0x76db6359 - BaseThreadInitThunk
  42: 0x770b7c24 - RtlGetAppContainerNamedObjectPath
  43: 0x770b7bf4 - RtlGetAppContainerNamedObjectPath`
```

**Comment by a7g4** [comment]
Related to #15

**Comment by a7g4** [comment]
Out of interest, do you know how much memory your video card has?
